name: awesome_extensions
description: An extension to the widget that helps to reduce the boilerplate and adds some helpful methods. and you can make responsive design.
version: 2.0.9
homepage: https://jayeshpansheriya.github.io/awesome_extensions
repository: https://github.com/jayeshpansheriya/awesome_extensions
issue_tracker: https://github.com/jayeshpansheriya/awesome_extensions/issues

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.10.0-0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
